### ISSUE TITLE
Connect to arduino nano

### ISSUE THREAD

**Issue by dmsergeevich63** [ronangaillard/logitech-mouse#4]
I connected nrf to arduino nano using the scheme (), but I can’t pair with the computer (Logitech Unifying USB Receiver)
In the logitech-mouse.h file, I changed:
#define DEFAULT_CE_PIN 7
#define DEFAULT_CS_PIN 8.
As far as I remember, I should indicate in PAIRING_MAC_ADDRESS mac the address of my logitech dongle, but how do I know it?
  Here is what I see in the serial port:
19: 34: 08.682 -> Starting
19: 34: 08.717 -> Trying to reconnect
19: 34: 09.405 ->
19: 34: 09.405 -> Unable to reconnect to dongle ... Pairing with any dongle ...
![15Безымянный](https://user-images.githubusercontent.com/47436708/63446304-08c17c00-c44b-11e9-98f8-27e13b94c40e.png)

**Comment by enscons** [comment]
I had similar issues... hook up a low esr 10 micro cap on the 5 volt terminals closed to the input of the nrf. This solved it for me. I follwed the given instructions bog standard and faced no issues

Sent from Yahoo Mail on Android 
 
  On Wed, 21 Aug 2019 at 21:08, dmsergeevich63<notifications@github.com> wrote:   
I connected nrf to arduino nano using the scheme (), but I can’t pair with the computer (Logitech Unifying USB Receiver)
In the logitech-mouse.h file, I changed:
#define DEFAULT_CE_PIN 7
#define DEFAULT_CS_PIN 8.
As far as I remember, I should indicate in PAIRING_MAC_ADDRESS mac the address of my logitech dongle, but how do I know it?
  Here is what I see in the serial port:
19: 34: 08.682 -> Starting
19: 34: 08.717 -> Trying to reconnect
19: 34: 09.405 ->
19: 34: 09.405 -> Unable to reconnect to dongle ... Pairing with any dongle ...

**Comment by ronangaillard** [comment]
This is normal. It's trying first to re-connect to the previous dongle it was connected to.

If it's the first boot you have obviously no previous connected dongle so after failing to the connect to the previous one it enters pairing mode.
